Guilds/urls.py
#Non project imports
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.views.generic import TemplateView

#Project imports
from Guilds import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #Beginning of added URLS
    path('UserEntry/', include('UserEntry.urls')),
    path('UserProfiles/', include('UserProfiles.urls')),
    path('LaunchGuild/', include('GuildCreation.urls')),
    path('GuildProfiles/', include('GuildProfiles.urls')),
    path('GuildPost/', include('GuildPosts.urls')),
    path('UserPost/', include('UserPosts.urls')),
    path('Follow/', include('Follow.urls')),
    path('Home', include('Home.urls')),
    path('UserSettings/', include('UserSettings.urls')),
    path('Search/', include('FullSearch.urls')),
    path('404test/', TemplateView.as_view(template_name='404.html')),
    path('Discover/', include('Discover.urls')),
    path('GroupChat/', include('GroupChat.urls')),
    path('Notifications/', include('Notifications.urls')),
    path('Logout/', include('UserLogout.urls')),
    path('Group', include('GroupPage.urls'))

]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.urls import path

from . import views

app_name = "Home"
urlpatterns = [
    path('', views.HomeView, name="Feed"),

]

UserEntry/urls.py
#Non project imports
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from .forms import UserLoginCustomForm

#Project imports
from . import views

app_name='UserEntry'
urlpatterns = [
    path('Login/', auth_views.login, {'template_name': 'UserEntry/Login.html', 'authentication_form': UserLoginCustomForm }, name="Login"),
    path('Register/', views.UserRegistrationView, name="Register"),
    url('Activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        views.Activate, name='Activate'),
    path('ActivationSent/', views.ActivationSent, name="ActivationSent"),

]

UserEntry/models.py
#Non project imports
from django.db import models

#Project imports


# Create your models here.

UserEntry/forms.py
#Non project imports
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User



#Project imports


#This form is present to allow for the presence of emails on the registration page for users
class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.', widget=forms.TextInput(attrs={'placeholder': 'Email'}), label='')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'password1': forms.PasswordInput(attrs={'placeholder': 'Password'}),
            'password2': forms.PasswordInput(attrs={'placeholder': 'Username'}),
        }

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(attrs={'placeholder': 'Password'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'placeholder': 'Repeat password'})

class UserLoginCustomForm(AuthenticationForm):
        username = forms.CharField(widget=forms.TextInput(attrs={'class':'validate','placeholder': 'Username'}))
        password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}))

UserEntry/views.py
#Non project imports
from django.contrib.auth import login, authenticate
from django.urls import reverse
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth.models import User
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags

#Project imports
from UserEntry.forms import UserRegistrationForm
from .tokens import AccountActivationToken
from UserProfiles.models import UserProfileModel 


#This view, as it's name implies, handles user registration
#It first checks if the request is GET or POST
#If it is POST the form is set to the UserRegistrationForm
#The user that will be created is made inactive, for later activation through email verification
#The form is then validated and saved to the database
#A set of email related varibles are setup to store the subject and details of the verification email
#The user is emailed with a verification email for their account
#Finally the user is redirected to the account verification notification page
#If it is NOT a Post request the page simply sets the form to UserRegistrationForm
#Finishing by returning the signup page.
def UserRegistrationView(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            User = form.save(commit=False)
            User.is_active = False
            User.save()
            Username = form.cleaned_data.get('username')
            UnHashedPassword = form.cleaned_data.get('password1')
            CurrentSite = get_current_site(request)
            MailSubject = 'Activate your account!'
            Message = render_to_string('UserEntry/AccountActivationEmailRaw.html', {
                'user': User,
                'domain': CurrentSite.domain,
                'uid':urlsafe_base64_encode(force_bytes(User.pk)).decode(),
                'token':AccountActivationToken.make_token(User),
            })
            MessageTemplated = render_to_string('UserEntry/AccountActivationEmail.html', {
                'user': User,
                'domain': CurrentSite.domain,
                'uid':urlsafe_base64_encode(force_bytes(User.pk)).decode(),
                'token':AccountActivationToken.make_token(User),
            })
            ToEmail = form.cleaned_data.get('email')
            Email = EmailMultiAlternatives('Verify your Guilds Social account!', Message, to=[ToEmail])
            Email.attach_alternative(MessageTemplated, "text/html")
            Email.send()
            return redirect('UserEntry:ActivationSent')

    else:
        form = UserRegistrationForm()

    return render(request, 'UserEntry/Register.html', {'form': form})

#This function does as its name implies
#It finds the user currently awaiting account validation through the validation url
#Proceeds to make that user active
#Save the setting
#And notifies the user
def Activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, user.DoesNotExist):
        user = None
    if user is not None and AccountActivationToken.check_token(user, token):
        ProfileVar = UserProfileModel()
        user.is_active = True
        user.save()
        ProfileVar.UserProfileRelation = user
        ProfileVar.save()
        login(request, user)
        return render(request, 'UserEntry/AccountVerificationNotificationSuccess.html')
    else:
        return render(request, 'UserEntry/AccountVerificationNotificationFailure.html')

def ActivationSent(request):
    return render(request, 'UserEntry/ActivationSent.html')

UserEntry/templates/UserEntry/AccountActivationEmailRaw.html
<!--This is the raw text version of the email sent to validate user accounts-->
<!--This is present in case the styled email does not function as intended-->

{% autoescape off %}
Hi {{ user.username }}
This is the last step to register on Guilds Social!
http://{{ domain }}{% url 'UserEntry:Activate' uidb64=uid token=token %}
{% endautoescape %}

UserEntry/templates/UserEntry/AccountActivationEmailWithoutInline.html
<!--This is the version of the verification email that is designed to be editable-->
<!--When you have finished editing this email HTML go to https://foundation.zurb.com/emails/inliner-v2.html and inline-->
<!--Then add the final version to AccountActivationEmail.html-->
<!--This email is styled using foundation 2 for emails (CSS version)-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <!-- The character set should be utf-8 -->
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width"/>
  <!-- Link to the email's CSS, which will be inlined into the email -->
  <link rel="stylesheet" href="assets/css/foundation-emails.css">
  <style>
    <!-- Your CSS to inline should be added here -->

  </style>
</head>

<body>
  <!-- Wrapper for the body of the email -->
  <table class="body" data-made-with-foundation>
    <tr>
      <!-- The class, align, and <center> tag center the container -->
      <td class="float-center" align="center" valign="top">
        <center>
          <!-- The content of your email goes here. -->
          <table class="container">
            <tr>
              <td>
                <table class="row">
                  <tr>
                    <th class="small-12 large-6 first columns">
                      <table>
                        <tr>
                          <th>
                            <center data-parsed="">
                              <img src="https://i.imgur.com/UQDcGs7.png" align="center" class="float-center image">
                            </center>
                          </th>
                        </tr>
                      </table>
                    </th>
                    <th class="small-12 large-6 last columns">
                      <p>
                        {% autoescape off %}
                        <h1>Hi <b>{{ user.username }}</b></h1><br/>
                        This is the last step to register on Guilds Social!
                        http://{{ domain }}{% url 'UserEntry:Activate' uidb64=uid token=token %}
                        {% endautoescape %}
                        <table class="button float-center">
                          <tr>
                            <td>
                              <table>
                                <tr>
                                  <td><a href="http://{{ domain }}{% url 'Activate' uidb64=uid token=token %}">Verify!</a></td>
                                </tr>
                              </table>
                            </td>
                          </tr>
                        </table>
                      </p>
                    </th>
                    <th class="expander">
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </center>
      </td>
    </tr>
  </table>
</body>
</html>

UserEntry/templates/UserEntry/AccountVerificationNotificationFailure.html
{% extends "UserEntry/Base.html" %}

{% load static %}

{% block Head %}

<link rel="shortcut icon" href="{% static 'UserEntry/Images/GuildLogoIcon.png' %}" type="image/png" />
<link rel="stylesheet" type="text/css" href="{% static 'UserEntry/CSS/AccountVerificationNotificationFailure.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
<title>Guilds, the social network where groups connect!</title>

{% endblock %}

{% block Content %}

<div class="row">

  <div class="col l12 s12 m12">

    <div class="card white" style="max-width: 30.25em; margin: auto; min-height: 20em; border-radius: 4px; padding-top: 3em; padding-bottom: 2em; padding-top: 2em; top: 4.5em; margin-bottom: 4.5em;">

      <div class="card-content black-text" style="padding-top: 2em; padding-bottom: 2em; text-align: center;">

        <span class="card-title" style="font-weight: bold; font-family: 'Noto Sans'; letter-spacing: 3px; font-size: 36px;">ERROR</span>

        <hr style="margin-top: 3em; margin-bottom: 2em;"/>

        <p style="color: black; margin: auto; font-size: 18px; font-family: 'Noto Sans';">Your verification link failed somehow</p>

        <p style="color: #A3A3A3; margin: auto; font-size: 18px; font-family: 'Noto Sans'; top: 2em; position: relative;">It may help to <a href="{% url 'UserEntry:Register' %}" style="color: #FF7723; letter-spacing: 1px;">re-try</a></p>

      </div>


    </div>

  </div>

</div>

{% endblock %}

UserEntry/templates/UserEntry/AccountVerificationNotificationSuccess.html
{% extends "UserEntry/Base.html" %}

{% load static %}

{% block Head %}

<link rel="shortcut icon" href="{% static 'UserEntry/Images/GuildLogoIcon.png' %}" type="image/png" />
<link rel="stylesheet" type="text/css" href="{% static 'UserEntry/CSS/AccountVerificationNotificationSuccess.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
<title>Guilds, the social network where groups connect!</title>

{% endblock %}

{% block Content %}

<div class="row">

  <div class="col l12 s12 m12">

    <div class="card white" style="max-width: 30.25em; margin: auto; min-height: 20em; border-radius: 4px; padding-top: 3em; padding-bottom: 2em; padding-top: 2em; top: 4.5em; margin-bottom: 4.5em;">

      <div class="card-content black-text" style="padding-top: 2em; padding-bottom: 2em; text-align: center;">

        <span class="card-title" style="font-weight: bold; font-family: 'Noto Sans'; letter-spacing: 3px; font-size: 36px;">ACCOUNT VERIFIED</span>

        <hr style="margin-top: 3em; margin-bottom: 2em;"/>

        <p style="color: black; margin: auto; font-size: 18px; font-family: 'Noto Sans';">Your account is now verified</p>

        <p style="color: #A3A3A3; margin: auto; font-size: 18px; font-family: 'Noto Sans'; top: 2em; position: relative;">You can now <a href="{% url 'UserEntry:Login' %}" style="color: #FF7723; letter-spacing: 1px;">login</a></p>

      </div>


    </div>

  </div>

</div>

{% endblock %}

UserEntry/templates/UserEntry/ActivationSent.html
{% extends "UserEntry/Base.html" %}

{% load static %}

{% block Head %}

<link rel="shortcut icon" href="{% static 'UserEntry/Images/GuildLogoIcon.png' %}" type="image/png" />
<link rel="stylesheet" type="text/css" href="{% static 'UserEntry/CSS/ActivationSent.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
<title>Guilds, the social network where groups connect!</title>

{% endblock %}

{% block Content %}

<div class="row">

  <div class="col l12 s12 m12">

    <div class="card white" style="max-width: 30.25em; margin: auto; min-height: 20em; border-radius: 4px; padding-top: 3em; padding-bottom: 2em; padding-top: 2em; top: 4.5em; margin-bottom: 4.5em;">

      <div class="card-content black-text" style="padding-top: 2em; padding-bottom: 2em; text-align: center;">

        <span class="card-title" style="font-weight: bold; font-family: 'Noto Sans'; letter-spacing: 3px; font-size: 36px;">EMAIL SENT</span>

        <hr style="margin-top: 3em; margin-bottom: 2em;"/>

        <p style="color: black; margin: auto; font-size: 18px; font-family: 'Noto Sans';">To login, click the verification link in the email we sent you!</p>

        <p style="color: #A3A3A3; margin: auto; font-size: 18px; font-family: 'Noto Sans'; top: 2em; position: relative;">Then go <a href="{% url 'UserEntry:Login' %}" style="color: #FF7723; letter-spacing: 1px;">here</a> to login</p>

      </div>


    </div>

  </div>

</div>

{% endblock %}

UserEntry/templates/UserEntry/Base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   <head>

     <!-- Meta tags -->
     <meta charset="utf-8">
     <!--Import Google Icon Font-->
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
     <!--Import materialize.css-->
     <link rel="stylesheet" type="text/css" href="{% static 'UserEntry/CSS/materialize.css' %}" />

     <!--Let browser know website is optimized for mobile-->
     <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
     {% block Head %}
     {% endblock %}

   </head>

   <body>

     {% block Content %}
     {% endblock %}

     <!-- Script tags used for Bootstrap -->
     <script type="text/javascript" src="{% static 'UserEntry/JavaScript/materialize.js' %}"></script>

   </body>

</html>

UserEntry/templates/UserEntry/Login.html
{% extends "UserEntry/Base.html" %}

{% load static %}

{% block Head %}

<link rel="shortcut icon" href="{% static 'UserEntry/Images/GuildLogoIcon.png' %}" type="image/png" />
<link rel="stylesheet" type="text/css" href="{% static 'UserEntry/CSS/Login.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
<title>Guilds, the social network where groups connect!</title>

{% endblock %}

{% block Content %}

<div class="row">

  <div class="col l12 s12 m12">

    <div class="card white" style="max-width: 30.25em; margin: auto; min-height: 35em; border-radius: 4px; padding-top: 3em; padding-bottom: 2em; padding-top: 2em; top: 4.5em; margin-bottom: 4.5em;">

      <div class="card-content black-text" style="padding-top: 2em; padding-bottom: 2em; text-align: center;">

        <div class="card-image" style="margin: auto; width: 15rem;">
          <img src="{% static 'UserEntry/Images/GuildLogoWithText.png' %}" />
        </div>

        <hr style="margin-top: 42px; margin-bottom: 42px;"/>

        <span class="card-title" style="font-weight: bold; font-family: 'Noto Sans'; letter-spacing: 3px; font-size: 36px; bottom: 3px;">LOGIN</span>

        <form method="post" style="margin-top: 42px;">
          {% csrf_token %}
          <div class="form-group">
            {% for field in form %}
            <p>
              {{ field }}
            </p>
            {% endfor %}
          </div>

          {% for field in form %}

            {% for error in field.errors %}

              <div class="error" role="alert">
                {{ error }}
              </div>

            {% endfor %}

          {% endfor %}


          <button type="submit" class="waves-effect waves-light btn" style="background-color: #FF7723; font-weight: bold; font-family: 'Noto Sans'; letter-spacing: 1px; float: right; top: 1.7em; margin: auto;">LOGIN</button> <br>

        </form>

      </div>


    </div>

  </div>

</div>

{% endblock %}

UserEntry/templates/UserEntry/Register.html
{% extends "UserEntry/Base.html" %}

{% load static %}

{% block Head %}

<link rel="shortcut icon" href="{% static 'UserEntry/Images/GuildLogoIcon.png' %}" type="image/png" />
<link rel="stylesheet" type="text/css" href="{% static 'UserEntry/CSS/Register.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
<title>Guilds, the social network where groups connect!</title>

{% endblock %}

{% block Content %}

<div class="row">

  <div class="col l12 s12 m12">

    <div class="card white" style="max-width: 30.25em; margin: auto; min-height: 51em; border-radius: 4px; padding-top: 3em; padding-bottom: 2em; padding-top: 2em; top: 4.5em; margin-bottom: 4.5em;">

      <div class="card-content black-text" style="padding-top: 2em; padding-bottom: 2em; text-align: center;">

        <div class="card-image" style="margin: auto; width: 15rem;">
          <img src="{% static 'UserEntry/Images/GuildLogoWithText.png' %}" />
        </div>

        <hr style="margin-top: 42px; margin-bottom: 42px;"/>

        <span class="card-title" style="font-weight: bold; font-family: 'Noto Sans'; letter-spacing: 3px; font-size: 36px; bottom: 3px;">REGISTER</span>

        <form method="post" style="margin-top: 42px;">
          {% csrf_token %}
          <div class="form-group">
            {% for field in form %}
            <p>
              {{ field }}
            </p>
            {% endfor %}
          </div>

          {% for field in form %}

            {% for error in field.errors %}

              <div class="error" role="alert">
                {{ error }}
              </div>

            {% endfor %}

          {% endfor %}


          <button type="submit" class="waves-effect waves-light btn" style="background-color: #FF7723; font-weight: bold; font-family: 'Noto Sans'; letter-spacing: 1px; float: right; top: 1.7em; margin: auto;">SIGN UP</button> <br>

        </form>

      </div>


    </div>

  </div>

</div>

{% endblock %}