Discover/urls.py
#Non project imports
from django.urls import path

#Project imports
from . import views

app_name="Discover"
urlpatterns = [
    path('', views.Discover, name="DiscoverPage")

]

FullSearch/urls.py
from django.urls import path

from . import views

app_name = "FullSearch"
urlpatterns = [
    path('', views.SearchView, name="Search")

]

GroupChat/urls.py
from django.urls import path

from . import views 

app_name="GuildChat"
urlpatterns = [
	path('',views.GroupChat,name="GroupChat")	

]

Guilds/urls.py
#Non project imports
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.views.generic import TemplateView

#Project imports
from Guilds import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #Beginning of added URLS
    path('UserEntry/', include('UserEntry.urls')),
    path('UserProfiles/', include('UserProfiles.urls')),
    path('LaunchGuild/', include('GuildCreation.urls')),
    path('GuildProfiles/', include('GuildProfiles.urls')),
    path('GuildPost/', include('GuildPosts.urls')),
    path('UserPost/', include('UserPosts.urls')),
    path('Follow/', include('Follow.urls')),
    path('Home', include('Home.urls')),
    path('UserSettings/', include('UserSettings.urls')),
    path('Search/', include('FullSearch.urls')),
    path('404test/', TemplateView.as_view(template_name='404.html')),
    path('Discover/', include('Discover.urls')),
    path('GroupChat/', include('GroupChat.urls')),
    path('Notifications/', include('Notifications.urls')),
    path('Logout/', include('UserLogout.urls')),
    path('Group', include('GroupPage.urls'))

]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.urls import path

from . import views

app_name = "Home"
urlpatterns = [
    path('', views.HomeView, name="Feed"),

]

UserProfiles/urls.py
#Non project imports
from django.urls import path

#Project imports
from . import views

app_name = 'UserProfiles'
urlpatterns = [
    path('UpdateProfile/', views.UpdateUserProfileView , name="UpdateProfile"),
    path('Profiles/<Username>/', views.UserProfileView, name="UserProfile")

]

UserSettings/urls.py
from django.urls import path
from . import views

app_name = 'UserSettings'
urlpatterns = [
    path('', views.SettingsLinkListView, name="UserSettings"),

]

UserSettings/models.py
from django.db import models

# Create your models here.

UserSettings/views.py
from django.shortcuts import render

from .FindUserGuild import FindUserGuild

# Create your views here.
def SettingsLinkListView(request):
    UserName = None
    UserGuild = None
    UserGuildModel = None
    UserGuildName = None
    UserGuildModelInvite = None

    try:
        UserName = request.user.username
        UserGuild = FindUserGuild(request.user)
        UserGuildModel = UserGuild.Guild
        UserGuildName = UserGuildModel.GuildName
        UserGuildModelInvite = UserGuildModel.GuildInvite

    except:
        UserName = request.user.username

    return render(request, 'UserSettings/Settings.html', {'UserName': UserName, 'UserGuild': UserGuild, 'UserGuildName':UserGuildName, 'UserGuildModelInvite': UserGuildModelInvite, 'UserName': request.user.username})

UserSettings/templates/UserSettings/Base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   <head>

     <!-- Meta tags -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

     <!-- Link tags -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
     <link rel="stylesheet" type="text/css" href="{% static 'UserProfiles/CSS/Base.css' %}" />
     <link rel="shortcut icon" href="{% static 'UserProfiles/Images/GuildLogoIcon.png' %}" type="image/png" />

     <!-- Head block to allow for the addition of CSS, title, etc -->
     {% block Head %}
     {% endblock %}

   </head>

   <body>

     <nav class="navbar fixed-top navbar-white bg-white">

       <div class="mx-auto dropdown DropDownButtonCentered">
         <button class="InvisibleButton "data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

           <div class="DropDownBlock1">

           </div>

           <div class="DropDownBlock2">

           </div>

           <div class="DropDownBlock2">

           </div>

         </button>

         <div class="dropdown-menu DropDownMenuCentered text-center" aria-labelledby="dropdownMenuButton">

           <img src="{% static 'UserProfiles/Images/GuildLogoIcon.png' %}" style="width: 2rem; height: 2rem; margin-bottom: 0.3rem;">

           <a class="dropdown-item" href="{% url 'Home:Feed' %}">Home</a>

           <a class="dropdown-item" href="{% url 'NotificationsApp:Notifications' %}" style="background-color: red; color: white;">Notifications</a>

           <a class="dropdown-item" href="{% url 'GuildChat:GroupChat' %}">GroupChat</a>

           <a class="dropdown-item" href="{% url 'Discover:DiscoverPage' %}">Discover</a>

           <a class="dropdown-item" href="{% url 'FullSearch:Search' %}">Search</a>

           <a class="dropdown-item" href="{% url 'UserProfiles:UserProfile' Username=UserName %}">Profile</a>

           <a class="dropdown-item" href="{% url 'UserSettings:UserSettings' %}">Settings</a>


         </div>

       </div>

     </nav>


     {% block Content %}
     {% endblock %}

     <!-- Script tags used for Bootstrap -->
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
   </body>

</html>

UserSettings/templates/UserSettings/Settings.html
{% extends "UserSettings/Base.html" %}
{% load static %}


{% block Head %}
<link rel="stylesheet" type="text/css" href="{% static 'GuildProfiles/CSS/GuildProfile.css' %}" />
<title>Your settings!</title>
{% endblock %}

{% block Content %}
<div class="container mx-auto text-center" style="width: 100%; background-color: white; margin-bottom: 1rem; border: grey solid 0.05rem; border-radius: 0.3rem; margin-top: 7rem; min-width: 18rem;">

  <div class="container" style="margin-top: 1rem;">
    <h1>Settings</h1> <p style="color: grey;">All the tools you need to get started</p>
  </div>


  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Update your profile</h5>
      <p class="card-text">Update your personal profile. Go here if you want to change your profile bio, link, image, or header!</p>
      <a href="{% url 'UserProfiles:UpdateProfile' %}" class="btn btn-default" style="border-color: #0099cc;">Jump</a>
    </div>
  </div>

  {% if  UserGuild != None %}
  <div class="card mx-auto">
    <div class="card-body">
      <h5 class="card-title">Update your guild profile</h5>
      <p class="card-text">Update your guilds profile. Go here if you want to change your guilds profile bio, link, image, or header!</p>
      <a href="{% url 'GuildProfiles:UpdateGuildProfile' %}" class="btn btn-default" style="border-color: #0099cc;">Jump</a>
    </div>
  </div>

  <div class="card mx-auto">
    <div class="card-body">
      <h5 class="card-title">Leave your current guild</h5>
      <p class="card-text">Exit your current guild. Clicking this will remove you from your current guild.</p>
      <a href="{% url 'GuildLaunch:LeaveGuild' %}" class="btn btn-default" style="border-color: red; color: red;">Jump</a>
    </div>
  </div>

  <div class="card mx-auto">
    <div class="card-body">
      <h5 class="card-title">Your guilds invite link</h5>
      <p class="card-text">Use this link to invite new people to your guild.</p>
      <a href="{% url 'GuildLaunch:JoinGuild' Key=UserGuildModelInvite %}">Copy my link address!</a>
    </div>
  </div>
  {% else %}

  <div class="card mx-auto">
    <div class="card-body">
      <h5 class="card-title">Create a new guild!</h5>
      <p class="card-text">Create a new guild and join it!</p>
      <a href="{% url 'GuildLaunch:GuildCreate' %}" class="btn btn-default" style="border-color: #ff5623; color: #ff5623;">Jump</a>
    </div>
  </div>

  {% endif %}

</div>


{% endblock %}