Discover/urls.py
#Non project imports
from django.urls import path

#Project imports
from . import views

app_name="Discover"
urlpatterns = [
    path('', views.Discover, name="DiscoverPage")

]

GuildPosts/urls.py
#Non project imports
from django.urls import path

#Project imports
from . import views

app_name = 'GuildPosts'
urlpatterns = [
    path('Post/', views.PostGuildView, name="GuildPost"),
    path('PostReply/<PostLink>', views.PostGuildReplyView, name="GuildReply"),
    path('Like/<PostLink>', views.PostGuildLikeView, name="Like")

]

GuildProfiles/urls.py
#Non project imports
from django.urls import path

#Project imports
from . import views

app_name='GuildProfiles'
urlpatterns = [
    path('UpdateGuildProfile/', views.UpdateGuildProfileView, name="UpdateGuildProfile"),
    path('<Guildname>/', views.GuildProfileView, name="GuildProfile")

]

Guilds/urls.py
#Non project imports
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.views.generic import TemplateView

#Project imports
from Guilds import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #Beginning of added URLS
    path('UserEntry/', include('UserEntry.urls')),
    path('UserProfiles/', include('UserProfiles.urls')),
    path('LaunchGuild/', include('GuildCreation.urls')),
    path('GuildProfiles/', include('GuildProfiles.urls')),
    path('GuildPost/', include('GuildPosts.urls')),
    path('UserPost/', include('UserPosts.urls')),
    path('Follow/', include('Follow.urls')),
    path('Home', include('Home.urls')),
    path('UserSettings/', include('UserSettings.urls')),
    path('Search/', include('FullSearch.urls')),
    path('404test/', TemplateView.as_view(template_name='404.html')),
    path('Discover/', include('Discover.urls')),
    path('GroupChat/', include('GroupChat.urls')),
    path('Notifications/', include('Notifications.urls')),
    path('Logout/', include('UserLogout.urls')),
    path('Group', include('GroupPage.urls'))

]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.urls import path

from . import views

app_name = "Home"
urlpatterns = [
    path('', views.HomeView, name="Feed"),

]

Discover/models.py
from django.db import models

# Create your models here.

Discover/views.py
#Non project imports
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

#Project imports
from GuildPosts.models import PostModel
from UserProfiles.models import UserProfileModel
from GroupChat.models import Message
from GroupChat.forms import ChatModelForm
from Notifications.models import Notification
from GuildProfiles.models import GuildProfileModel
from .FindUserGuild import FindUserGuild
from GuildPosts.models import Like

# Create your views here.

def Discover(request):
    PostList = PostModel.objects.filter()
    UserName = request.user.username
    NotificationLi = Notification.objects.filter(UserNotify = request.user)
    MessageList = Message.objects.filter(GuildId = FindUserGuild(request.user.id))
    Temp = []
    Temp2 = []
    FullList = []

    if request.method == 'POST':
        form = ChatModelForm(request.POST)
        if form.is_valid():
            Chat = Message()
            Chat.UserId = request.user
            Chat.GuildId = FindUserGuild(request.user.id)
            Chat.MessageBody = form.cleaned_data['MessageBody']
            Chat.ProfId = UserProfileModel.objects.get(UserProfileRelation = request.user)
            Chat.save()
    else:
        form = ChatModelForm()

    for k in PostList:
        try:
            Temp.append(k.PostGuildProfile.GuildProfileImage)
        except:
            Temp.append("")
        Temp.append(k.PostGuild.GuildName)
        Temp.append(k.PostDate)
        Temp.append(k.PostBody)
        Temp.append(k.PostLink)
        Temp.append(len(Like.objects.filter(PostRelation=k)))
        try:
            Temp2.append(UserProfileModel.objects.get(UserProfileRelation=((MemberListModel.objects.get(Guild=k.PostGuild)).GuildUser1)))
        except:
            pass
        try:
            Temp2.append(UserProfileModel.objects.get(UserProfileRelation=((MemberListModel.objects.get(Guild=k.PostGuild)).GuildUser2)))
        except:
            pass
        try:
            Temp2.append(UserProfileModel.objects.get(UserProfileRelation=((MemberListModel.objects.get(Guild=k.PostGuild)).GuildUser3)))
        except:
            pass
        try:
            Temp2.append(UserProfileModel.objects.get(UserProfileRelation=((MemberListModel.objects.get(Guild=k.PostGuild)).GuildUser4)))
        except:
            pass
        try:
            Temp2.append(UserProfileModel.objects.get(UserProfileRelation=((MemberListModel.objects.get(Guild=k.PostGuild)).GuildUser5)))
        except:
            pass
        Temp.append(Temp2)
        FullList.append(Temp)
        Temp = []
        Temp2 = []

    return render(request, 'Discover/Discover.html', {'FullList':FullList,'form':form, 'NotificationLi':NotificationLi, 'MessageList':MessageList,'PostList':PostList, 'UserName':request.user.username})

Discover/templates/Discover/Discover.html
{% extends "Discover/Base.html" %}
{% load static %}


{% block Head %}
<link rel="stylesheet" type="text/css" href="{% static 'Discover/CSS/Discover.css' %}" />
<title>Explore!</title>
{% endblock %}

{% block Content %}

<div class="container">
  <div class="row" style="top: 3em; position: relative;">
    <div class="col l6 m12 s12 offset-l3" style="overflow: hidden; text-align: center;">
      <span style="font-size: 75px; font-family: 'Noto Sans'; text-align: center;">Explore</span>
      <br/>
      <h4 style="font-family: 'Noto Sans';">Find new guilds</h4>
    </div>
  </div>
</div>

<div class="card white" style="position: relative; top: 7em; min-height: 29.5em; margin-bottom: 0;">

  <div class="container">
  <div class="row">
    <div class="col l6 m12 s12 offset-l3">

  {% for i in FullList %}

  <div class="card horizontal" style="height: 15em; max-width: 40em; margin: auto; margin-top: 1em; overflow: hidden;">
    <div class="card-image">
      <a href="{% url 'GuildProfiles:GuildProfile' Guildname=i.1 %}"><img src="../../../MediaStorage/{{ i.0 }}" style="width: 15em; height: 15em; border-width: 1px; border-style: solid; border-color: black; object-fit: cover;"></a>
    </div>
    <div class="card-stacked">
      <div class="card-content">
        <a href="{% url 'GuildProfiles:GuildProfile' Guildname=i.1 %}"><span class="card-title" style="float: left; font-weight: bold; font-family: 'Noto Sans'; font-size: 35px; color: black;">{{ i.1|truncatechars:10   }}<h6 style="float: right;">{{ i.2 }}</h6></span></a>




        <div style="float: left; bottom: 1em; position: relative;">

          <span>Members:</span>

          {% for t in i.6 %}
            <img src="../../..{{ t.UserProfileImage.url }}" style="width: 30px; height: 30px; position: relative; border-width: 1px; border-color: grey; border-style: solid; object-fit: cover; margin-left: 1em; top: 0.6em;" />
          {% endfor %}


        </div>

        <br/>
        <br/>
        <br/>

        <p style="float: left; position: relative; max-width: 20em; max-height: 3em; height: 3em; width: 20em; word-wrap: break-word; text-align: left; font-size: 15px;">{{ i.3|truncatechars:111 }}</p>

        <br/>
        <br/>
        <br/>
        <br/>

        <a href="{% url 'GuildPosts:GuildReply' PostLink=i.4  %}" style="position: relative; float: left;">
          <i class=" material-icons" style="color: black;">
            reply
          </i>
        </a>

        <a href="{% url 'GuildPosts:Like' PostLink=i.4  %}" style="position: relative; float: left; padding-left: 1em;">
          <i class=" material-icons" style="color: black;">
            favorite
          </i>
          <p style="position: relative; left: 1.5em; top: -2em; color: black; font-family: 'Noto Sans';">{{ i.5 }}</p>
        </a>

      </div>
    </div>
  </div>

  {% endfor %}

    </div>
  </div>
  </div>

</div>


<!--
<div class="PostContainer mx-auto">
  {% for i in PostList reversed%}
  <div class="card mx-auto m-5" style="">
    <div class="card-body text-center">
      <p class="card-text"> <h2><a href="{% url 'GuildProfiles:GuildProfile' Guildname=i.PostGuild.GuildName  %}" style="color: black;">Post by: {{ i.PostGuild.GuildName }}</a></h2> <br/> {{ i.PostBody }} <br/> <h4 style="color: grey; padding-top: 1rem;">Posted on: {{ i.PostDate }}</h4> <h4><a href="{% url 'GuildPosts:Like' PostLink=i.PostLink  %}">sdsdffdsa</a></h4> <h4><a href="{% url 'GuildPosts:GuildReply' PostLink=i.PostLink  %}">sdsdffdsa</a></h4> </p>
    </div>
  </div>
  {% endfor %}
  <div class="card mx-auto m-3">
    <div class="card-body text-center">
      <p class="card-text">This is the end of the posts!</p>
      <small style="color: grey;"><a href="#top">Return to top?</a></small>
    </div>
  </div>
</div>
-->
{% endblock %}