Discover/urls.py
#Non project imports
from django.urls import path

#Project imports
from . import views

app_name="Discover"
urlpatterns = [
    path('', views.Discover, name="DiscoverPage")

]

FullSearch/urls.py
from django.urls import path

from . import views

app_name = "FullSearch"
urlpatterns = [
    path('', views.SearchView, name="Search")

]

GroupChat/urls.py
from django.urls import path

from . import views 

app_name="GuildChat"
urlpatterns = [
	path('',views.GroupChat,name="GroupChat")	

]

Guilds/urls.py
#Non project imports
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.views.generic import TemplateView

#Project imports
from Guilds import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #Beginning of added URLS
    path('UserEntry/', include('UserEntry.urls')),
    path('UserProfiles/', include('UserProfiles.urls')),
    path('LaunchGuild/', include('GuildCreation.urls')),
    path('GuildProfiles/', include('GuildProfiles.urls')),
    path('GuildPost/', include('GuildPosts.urls')),
    path('UserPost/', include('UserPosts.urls')),
    path('Follow/', include('Follow.urls')),
    path('Home', include('Home.urls')),
    path('UserSettings/', include('UserSettings.urls')),
    path('Search/', include('FullSearch.urls')),
    path('404test/', TemplateView.as_view(template_name='404.html')),
    path('Discover/', include('Discover.urls')),
    path('GroupChat/', include('GroupChat.urls')),
    path('Notifications/', include('Notifications.urls')),
    path('Logout/', include('UserLogout.urls')),
    path('Group', include('GroupPage.urls'))

]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.urls import path

from . import views

app_name = "Home"
urlpatterns = [
    path('', views.HomeView, name="Feed"),

]

Notifications/urls.py
from django.urls import path

from . import views

app_name = "NotificationsApp"
urlpatterns = [
    path('', views.Notifications, name="Notifications")

]

UserProfiles/urls.py
#Non project imports
from django.urls import path

#Project imports
from . import views

app_name = 'UserProfiles'
urlpatterns = [
    path('UpdateProfile/', views.UpdateUserProfileView , name="UpdateProfile"),
    path('Profiles/<Username>/', views.UserProfileView, name="UserProfile")

]

Notifications/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Notification(models.Model):
    UserNotify = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    NotifyMessage = models.CharField(max_length=100)

Notifications/views.py
from django.shortcuts import render

from .models import Notification

# Create your views here.
def Notifications(request):
    NotificationLi = Notification.objects.filter(UserNotify = request.user)
    return render(request, 'Notifications/Notifications.html', {'NotificationLi':NotificationLi, 'Username':request.user.username})

Notifications/templates/Notifications/Base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   <head>

     <!-- Meta tags -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

     <!-- Link tags -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
     <link rel="stylesheet" type="text/css" href="{% static 'Notifications/CSS/Base.css' %}" />
     <link rel="shortcut icon" href="{% static 'Notifications/Images/GuildLogoIcon.png' %}" type="image/png" />

     <!-- Head block to allow for the addition of CSS, title, etc -->
     {% block Head %}
     {% endblock %}

   </head>

   <body>

     <nav class="navbar fixed-top navbar-white bg-white">

       <div class="mx-auto dropdown DropDownButtonCentered">
         <button class="InvisibleButton "data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

           <div class="DropDownBlock1">

           </div>

           <div class="DropDownBlock2">

           </div>

           <div class="DropDownBlock2">

           </div>

         </button>

         <div class="dropdown-menu DropDownMenuCentered text-center" aria-labelledby="dropdownMenuButton">

           <img src="{% static 'UserProfiles/Images/GuildLogoIcon.png' %}" style="width: 2rem; height: 2rem; margin-bottom: 0.3rem;">

           <a class="dropdown-item" href="{% url 'Home:Feed' %}">Home</a>

           <a class="dropdown-item" href="{% url 'NotificationsApp:Notifications' %}" style="background-color: red; color: white;">Notifications</a>

           <a class="dropdown-item" href="{% url 'GuildChat:GroupChat' %}">GroupChat</a>

           <a class="dropdown-item" href="{% url 'Discover:DiscoverPage' %}">Discover</a>

           <a class="dropdown-item" href="{% url 'FullSearch:Search' %}">Search</a>

           <a class="dropdown-item" href="{% url 'UserProfiles:UserProfile' Username=Username %}">Profile</a>

           <a class="dropdown-item" href="{% url 'UserSettings:UserSettings' %}">Settings</a>


         </div>

       </div>

     </nav>


     {% block Content %}
     {% endblock %}

     <!-- Script tags used for Bootstrap -->
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
   </body>

</html>

Notifications/templates/Notifications/Notifications.html
{% extends "Notifications/Base.html" %}

{% load static %}

{% block Head %}

<link rel="stylesheet" type="text/css" href="{% static 'Notifications/CSS/Notifications.css' %}" />

{% endblock %}

{% block Content %}

<div class="NotificationContainer mx-auto">
  {% for i in NotificationLi %}
  <div class="card mx-auto m-5" style="">
    <div class="card-body text-center">
      <p class="card-text"> {{i.NotifyMessage}} </p>
    </div>
  </div>
  {% endfor %}
  <div class="card mx-auto m-3">
    <div class="card-body text-center">
      <p class="card-text">This is the end of your notifications!</p>
      <small style="color: grey;"><a href="#top">Return to top?</a></small>
    </div>
  </div>
</div>

{% endblock %}